# Names: Allan Sur, Jason Songvilay
# RedIDs: 821444631, 821071661
# Edoras IDs: cssc3455, cssc3454
# Course: CS530-03-Spring2021
# Assignmt 2: Part II


g++-std=c++11
main:
	g++ -std=c++11 -c pagetable.cpp byu_tracereader.c output_mode_helpers.c
	g++ -o pagetable pagetable.o byu_tracereader.o output_mode_helpers.o

clean:
	rm *.o















# CXX=g++

# CXXFLAGS=-std=c++11 -g

# pagetable : main.cpp pagetable.o byu_tracereader.o
# 	$(CXX) $(CXXFLAGS) -o pagetable $^

# pagetable.o : pagetable.h pagetable.cpp

# byu_tracereader.o : byutr.h byu_tracereader.c

# clean :
# 	rm *.o pagetable